# Generated by Django 2.2.3 on 2019-11-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='coordinate',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.PokemonEntity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
