# Generated by Django 2.2.3 on 2019-11-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20191120_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='coordinate',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon'),
            preserve_default=False,
        ),
    ]
